#!/bin/bash
#
# a simple setup script for dply or Digital Ocean
#
# This assumes an Ubuntu 16.04 instance.
#
# Use:
#
# #cloud-config
#
# runcmd:
#   -  curl https://raw.githubusercontent.com/ScriptGadget/serverless-slack-join/master/cloud-setup | bash
#
###########################################################################################################

setup_all () {
    # set the environment
    export HOME=/root
    cd $HOME

    touch "LOADING_PLEASE_WAIT"

    # packages
    apt-get update
    apt-get install -y git-core
    apt-get install -y build-essential libssl-dev

    # Node (for grunt)
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
    nvm install 6 node # install Nodejs 6
    npm install -g serverless

    # Clone the project
    git clone https://github.com/ScriptGadget/serverless-slack-join.git
    pushd serverless-slack-join
    npm install
    popd

    # watch for the README to appear before trying to use anything.
    echo "Done"
    rm LOADING_PLEASE_WAIT
    echo "The system is ready. You may need to logout and log back to set your environment correctly." >  README
}

setup_all
