# Easily invite users to your Slack!
#
# For full config options, check the docs:
#    docs.serverless.com

service: serverless-slack-join

provider:
  name: aws
  runtime: nodejs4.3

functions:
  join:
    handler: handler.join
    events:
      - http:
          path: join
          method: post
